import { type Options, defaultSchema } from "rehype-sanitize";

const attributes = defaultSchema.attributes ?? {};

/**
 * GitHub-style Markdown plus the properties generated by our own image and embed
 * plugins. Raw author-supplied HTML is reduced to this schema before serialization.
 */
export const markdownSanitizeSchema: Options = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "figure",
    "figcaption",
    "iframe",
  ],
  attributes: {
    ...attributes,
    code: [
      ...(attributes.code ?? []),
      ["className", "language-math", "math-inline"],
    ],
    div: [...(attributes.div ?? []), ["className", "math-display"]],
    figure: [...(attributes.figure ?? []), "className"],
    img: [
      ...(attributes.img ?? []),
      "srcSet",
      "sizes",
      "width",
      "height",
      "loading",
      "decoding",
    ],
    iframe: [
      "src",
      "title",
      "loading",
      "referrerPolicy",
      "allow",
      "allowFullScreen",
      "sandbox",
      "className",
    ],
  },
};
